config/routes.rb
Ipdb::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/rate' => 'rater#create', :as => 'rate'
 devise_for :users
  resources :podcasts
  mount Commontator::Engine => '/commontator'
  
  root "pages#home"
  get "about" => "pages#about"
  get "profile" => "pages#profile"
  get "users" => "user#index"
  get "user/:id", :to => "user#show", :as => :user
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :default_url => "/images/ipdb.png",  :styles => {:medium => "250x250", :thumb => "100x100>"}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	acts_as_commontable
	letsrate_rateable
end

app/models/podcast_search.rb
class PodcastSearch < ActiveRecord::Base
  extend Textacular
  #attr_accessible :query
  attr_accessor :query

  belongs_to :searchable, polymorphic: true

  def results
    if @query.present?
      self.class.search(@query).preload(:searchable).map!(&:searchable).uniq.sort_by{|e| -e.created_at.to_i}
    else
      Search.none
    end
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :podcasts
  has_attached_file :profile_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :profile_image, :content_type => %w(image/jpeg image/jpg image/png)
  letsrate_rater
  acts_as_commontator

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
 
  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  	def index
      @comments = @commentable.comments
    end

    def new
      @comment = @commentable.comments.new
    end

    def create
      @comment = @commentable.comments.new(params[:comments])
      if @comment.save
        redirect_to @commentable, notice: "Comment created."
      else
        render :new
      end
    end

  private

    def load_commentable
      resource, id = request.path.split('/')[1, 2]
      @commentable = resource.singularize.classify.constantize.find(id)
    end

    # def load_commentable
    #   klass = [Article, Photo, Event].detect { |c| params["#{c.name.underscore}_id"] }
    #   @commentable = klass.find(params["#{klass.name.underscore}_id"])
    # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def profile
  	@podcasts = Podcast.all
  end
end

app/controllers/podcasts_controller.rb
require 'feedzirra'
require 'nokogiri'
require 'open-uri'

class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
if params[:search].present?
      @podcasts = PodcastSearch.new(query: params[:search]).results
      @paginate = Kaminari.paginate_array(@podcasts).page(params[:page])

    else
      @podcasts = Podcast.all.order('created_at ASC').page(params[:page])
      @paginate = Podcast.all.order('created_at DESC').page(params[:page])
    end
    @users= User.all
    @comments = Comment.all

  end

  def show
    @itunes = Nokogiri::HTML(open(@podcast.episodes))
    @itunesdata = @itunes.css('body')
    @episodesdata = @itunes.css('tr.podcast-episode')
    @feed = Feedzirra::Feed.fetch_and_parse(@podcast.episodes)
    @podcast = Podcast.find(params[:id])
    @commentable = @podcast
    @comments = @commentable.comments
    @comment = Comment.new
    @data = Rate.all
  end

  def new
    @podcast = current_user.podcasts.build
  end

  def edit
  end

  def create
    @podcast = current_user.podcasts.build(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render action: 'show', status: :created, location: @podcast }
      else
        format.html { render action: 'new' }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url }
      format.json { head :no_content }
    end
  end

  private
    def set_podcast
      @podcast = Podcast.find(params[:id])

    end

    def podcast_params
      params.require(:podcast).permit(:description, :episodes, :name, :image)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_i, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def index
		@users= User.all
		@podcasts = Podcast.all
	end

  def show
  	@podcasts = Podcast.all
    @user = User.find(params[:id])
    @users= User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comments.html.erb
<div id="comments">
<% @comments.each do |comment| %>
  <div class="comment">
    <%= simple_format comment.content %>
  </div>
<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :comments, rows: 8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<%= render 'comments' %>


<p><%= link_to "New Comment", [:new, @commentable, :comment] %></p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

app/views/layouts/_navi.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <a class="navbar-brand" href="#"><img src="//ipdb.net/ipdb-logo.png"></a>
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav navbar-left">
			<li><%= link_to "<i class='fa fa-home'></i> Home".html_safe, root_path, :title => "Home" %></li>
			<li><%= link_to "<i class='fa fa-list'></i> Podcasts".html_safe, podcasts_path %></li>
			<li><%= link_to "<i class='fa fa-users'></i> Users".html_safe, users_path %></li>
	    <% if user_signed_in? %>
		<li class="dropdown">
	    	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= fa_icon "cogs" %></a>
	    	<ul class="dropdown-menu">
	    		<li><%= link_to "Edit Profile".html_safe, edit_user_registration_path %></li>
		  		<li><%= link_to "View Profile", "../user/" + "#{current_user.id}" %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
    </li>
    <%= form_tag(podcasts_path, :method => "get", id: "search-form", class: "navbar-form navbar-right") do %>
    <div class="form-group">
			<%= text_field_tag :search, params[:search], placeholder: "Search Podcasts", class: "form-control" %>
    </div>
 			<%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
 		<% end %>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <%= form_tag(podcasts_path, :method => "get", id: "search-form", class: "navbar-form navbar-right") do %>
        <div class="form-group">
		<%= text_field_tag :search, params[:search], placeholder: "Search Podcasts", class: "form-control" %>
        </div>
 		<%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
	    	</ul>
	   </li>
 		<% end %>

	   <% end %>
			
	   </ul>
	 </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ipdb</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/navi" %>



<div class="container">
<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
<h1>About</h1>
<p>Podcasting has become a quick and easy way for people to connect with like-minded people via the spoken word. We view each podcaster as a leader: some have a huge following while some are just starting out. Bottom line: we want to celebrate you and this database is here to serve the podcaster first and foremost. We anticipate some wonderful benefits with our site.</p>

<h4>PERSONAL PROFILE</h4>

<p>The ability to maintain a personal profile is one of the unique features that makes IPDB stand out from podcast delivery sites. Your personal profile is equally as important as the content that you are sharing with the world. As a podcast celebrity, people will be able to research your podcasts and rate and review your work. This feedback is valuable for your brand and your efforts in this field.</p>

<h4>TALENT SCOUTS</h4>

<p>Talent scouts have already given their voice of approval for IPDB as they are constantly looking for voice over talent. This is where your personal profile become a value tool. This is much like the celebrities on IMDB who will tell you that their profile helps tremendously in their career.</p>

<p>These are just a few benefits that we would like to share. Keep checking back as we are in development. 
If you would like to be a Beta Tester, please email info@ipdb.net.</p>
</div>
<script>
	$('body').addClass('about');
</script>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to IPDB!</h1>
     <p>
		 <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>    
</div>

<script>
	$('body').addClass('home');
</script>

app/views/pages/profile.html.erb
<div class="row">
<div class="col-md-3">
<h2 style="text-align:center;"><%= "#{current_user.first_name} #{current_user.last_name}" %></h2>
<br>
	<img src=" <%= "#{current_user.profile_image}" %>" class="img-circle"><hr />
	<p><%= "#{current_user.description}" %></p>
  <div class="row">
    <div class="col-md-6">
      <h3 style="text-align:center;">Followers</h3>
      <h3 style="text-align:center;">52</h3>
    </div>
    <div class="col-md-6">
      <h3 style="text-align:center;">Following</h3>
      <h3 style="text-align:center;">0</h3>
    </div>
  </div>
  <hr />
  <div class="social">
    <a class="btn btn-primary btn-block"><span class="glyphicon glyphicon-plus"></span> Follow</a>
    <a class="btn btn-default btn-block"><span class="glyphicon glyphicon-share"></span> Share</a>
  </div>
</div>
<div class="col-md-8 col-md-offset-1">
<h3>Podcasts by me</h3>
<ul class="podcast-profile">
  <% @podcasts.each do |podcast| %>
          <% if podcast.user == current_user %>
      <li class="well col-md-4">
      <%= link_to image_tag(podcast.image.url) + '', podcast %><br>
        <h4><%= podcast.Name %></h4>
          <%= link_to 'Edit',  edit_podcast_path(podcast), class: 'btn btn-warning' %>
          <%= link_to 'Delete', podcast, class: 'btn btn-danger' ,method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      </li>
    <% end %>
    </ul>
    <hr class="clear" />  
    <div class="tab-info">
    <ul id="tabs" class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">About</a></li>
      <li><a href="#profile" data-toggle="tab">Education</a></li>
      <li><a href="#home" id="tab" data-toggle="tab" >Work</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade in active" id="home">
        <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
      </div>
      <div class="tab-pane fade" id="profile">
        <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
      </div>
      <div class="tab-pane fade" id="dropdown1">
        <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
      </div>
      <div class="tab-pane fade" id="dropdown2">
        <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
      </div>
    </div>
  </div>
</div>
</div>
<br>

app/views/podcasts/_form.html.erb
<%= form_for(@podcast) do |f| %>
  <% if @podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% @podcast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h4><%= f.label :name %></h4>
    <%= f.text_field :name, class: "form-control" %><br>
    <h4><%= f.label :description %></h4>
    <%= f.text_area :description, class: "form-control", :rows => '5' %><br>
    <h4><%= f.label :image %></h4>
    <%= f.file_field :image, class: "form-control" %><br>
    <h4><%= f.label :episodes %> (URL of Podcasts)</h4>
    <%= f.text_field :episodes, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
     <%= link_to 'Delete', @podcast, class: "btn btn-danger" , method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>

<% end %>

app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>
<% if @podcast.user == current_user %>
<%= render 'form' %>
<% else %>
<h4>You cannot edit this Podcast</h4>
<% end %>
<%= link_to 'Show', @podcast %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'Add New Podcast', new_podcast_path, class: "btn btn-primary btn-lg pull-right" %>
<% end %>

<hr class="clear" />
<%= form_tag({:controller=>"podcasts", :action=>"index"}, :method=> "get") do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :class => "btn btn-primary" %>


<div class="podcast">
<h1>Listing podcasts</h1>
<%= if defined? @paginate then paginate @paginate else end %>
<hr />
    <% @podcasts.each do |podcast| %>

      <li class="well col-xs-5 col-md-2">


      <%= link_to image_tag(if podcast.image_url.blank? then podcast.image else podcast.image_url end) + '', podcast, :class => "podcast-img" %><br>
        <h4><%= podcast.name %></h4>

        <%= rating_for podcast %>
        <br>
        Published by:
        <% @users.each do |user| %>
        <% if podcast.user == user %>
          <%= link_to (user.first_name + ' ' + user.last_name) ,"user/#{user.id}" %><br>
        <% if podcast.user == current_user %>
          <%= link_to 'Edit',  edit_podcast_path(podcast), class: 'btn btn-warning' %>
          <%= link_to 'Delete', podcast, class: "btn btn-danger" , method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        <% end %>
        <% end %>
      </li>
    <% end %>
</div>
<%= if defined? @paginate then paginate @paginate else end %>

<% end %>

app/views/podcasts/new.html.erb
<h1>New podcast</h1>

<%= render 'form' %>

<%= link_to 'Back', podcasts_path %>

app/views/podcasts/show.html.erb
<% @itunesdata.each do | itunes | %>
    <% @title = itunes.css(".left h1").text %>
    <% description = itunes.css('.product-review p').text %>
    <% @img = itunes.css(".lockup.product.podcast img.artwork").map { |link| link['src'] }.first %>


<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-md-3">

	<h3><%= if defined? @title then @title else @podcast.name end %></h3>
	<img src="<%= if @podcast.image_url.blank? then @podcast.image else @podcast.image_url end %>" style="width:100%;">
	<%= rating_for @podcast %>
		<h4>Number of Episodes : <%= if @episodesdata.empty? then @feed.entries.count else @episodesdata.count end %></h4>
		<p><%= @podcast.description %></p>
		<p><%= description %></p>
		<a class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Follow</a>
		<a class="btn btn-default"><span class="glyphicon glyphicon-share"></span> Share</a>
	</div>
	<div class="col-md-8 col-md-offset-1">
   <% end %>
	<%= commontator_thread(@podcast) %>
	  <h4>Episodes:</h4>


	  <!-- itunes feed -->
		<% if @episodesdata.empty? then else @episodesdata.first( if @episodesdata.count > 15 then 15 else @episodesdata.count end).each do |episode| %>
		     <% show = if defined? episode["audio-preview-url"] then episode["audio-preview-url"] else end %>
		     <% info = if defined? episode.css('.text').text then episode.css('.text').text else end %>
		     <li class="well"><p><%= info %></p>
					<audio controls>
						<source src="<%= show %>">
					</audio>
				 </li>

		 <% end %>
		 <% end %>
		<!-- rss feeds -->
	  <% if defined? @feed.entries then @feed.entries.first(15).each do |t| %>
		<li class="well">
			<h4><%= link_to "#{t.title}", "#{t.url}" %></h4>
			<p><%=sanitize t.summary %></p>
			<%=t.author%>
			<%=t.content%>
			<audio controls>
            <source src="<%= if defined? t.enclosure_url then t.enclosure_url else t.image end %>" type="audio/mpeg">
            Your browser does not support the audio element.
          </audio>
		</li>
		<% end %>
	<% end %>
	</div>
</div>

<script>
	$('span.thread_new_comment_link a').addClass('btn  btn-primary');
	$('.thread a:first').addClass('btn btn-primary btn-block');
</script>
<% if @podcast.user == current_user %>
<%= link_to 'Edit', edit_podcast_path(@podcast) %> |
<%= link_to 'Back', podcasts_path %>
<% end %>

app/views/user/edit.html.erb
<h1>Editing User</h1>
<% if user == current_user %>
<%= render 'form' %>
<% else %>
<h4>You cannot edit this User</h4>
<% end %>
<%= link_to 'Show', user %> |
<%= link_to 'Back', podcasts_path %>

app/views/user/index.html.erb
<!-- USERS -->
<% @users.each do |user| %>
	<div class="col-md-3">
	<h4><%= link_to (if defined? user.first_name then user.first_name else end  + ' ' + if defined? user.last_name then user.last_name else end) ,"user/#{user.id}" %></h4>
   <img src=" <%= "#{user.profile_image}" %>" class="img-circle" style="width:150px; height:150px;">
  </div>
<% end %>

app/views/user/show.html.erb
<div class="row">
<div class="col-md-3">
<h2 class="username"><%= if @user.first_name.empty? then ' '  else @user.first_name end  + ' ' + if @user.last_name.empty? then ' ' else @user.last_name end %></h2>
<br>
  <img src=" <%= @user.profile_image %>" class="img-circle">
  <div class="social">
    <%= link_to '<i class="fa fa-facebook-square fa-2x"></i>'.html_safe,  'http://facebook.com/' + @user.facebook if @user.facebook.present? %>
    <%= link_to '<i class="fa fa-twitter-square fa-2x"></i>'.html_safe, 'http://twitter.com/' + @user.twitter if @user.twitter.present? %>
    <%= link_to '<i class="fa fa-pinterest-square fa-2x"></i>'.html_safe, 'http://pinterest.com/' + @user.pinterest if @user.pinterest.present? %>
    <%= link_to '<i class="fa fa-instagram fa-2x"></i>'.html_safe, 'http://instagram.com/' + @user.instagram if @user.instagram.present? %>
    <%= link_to '<i class="fa fa-linkedin-square fa-2x"></i>'.html_safe, 'http://linkedin.com/' + @user.linkedin if @user.linkedin.present? %>
</div>
<br>
  <p><%= @user.description %></p>
  <div class="row">

 <!-- <div class="followers">
      <div class="col-md-6">
          <h3>Followers</h3>
          <h3>52</h3>
        </div>
        <div class="col-md-6">
          <h3>Following</h3>
          <h3>0</h3>
      </div>
    </div> -->
  </div>
  <hr />
  <div class="social">
    <a class="btn btn-primary btn-block"><span class="glyphicon glyphicon-plus"></span> Follow</a>
    <a class="btn btn-default btn-block"><span class="glyphicon glyphicon-share"></span> Share</a>
  </div>
</div>
<div class="col-md-8 col-md-offset-1">
<h3>Podcasts by me</h3>
<ul class="podcast-profile">
  <% @podcasts.each do |podcast| %>
    <% if podcast.user == @user %>
      <li class="well col-md-4">
      <%= link_to image_tag(if podcast.image_url.blank? then podcast.image else podcast.image_url end) + '', podcast %><br>
        <h4><%= podcast.name %></h4>
          <% if podcast.user == current_user %>
          <%= link_to 'Edit',  edit_podcast_path(podcast), class: 'btn btn-warning' %>
          <%= link_to 'Delete', podcast, class: 'btn btn-danger' ,method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      </li>
      <% end %>
    <% end %>
    </ul>
    <hr style="clear:both;" />      
    <div class="tab-info">
    <ul id="tabs" class="nav nav-tabs">
      <li class="active"><a href="#home" data-toggle="tab">About</a></li>
      <li><a href="#profile" data-toggle="tab">Education</a></li>
      <li><a href="#work" id="tab" data-toggle="tab" >Work</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade in active" id="home">
        <p><%= @user.about %></p>
      </div>
      <div class="tab-pane fade" id="profile">
        <p><%= @user.education %></p>
      </div>
      <div class="tab-pane fade" id="work">
        <p><%= @user.work %></p>
      </div>
    </div>
    </div>
</div>
</div>
<br>